name: main
on:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [7.2, 7.3, 7.4, 8.0]
        stability: [prefer-lowest, prefer-stable]
    name: Tests on ${{ matrix.php }} - ${{ matrix.stability }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
      - name: Install Dependencies
        run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-suggest
      - name: Run Tests
        run: vendor/bin/phpunit
  code_styles:
    runs-on: ubuntu-latest
    name: Code Styles
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache Dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-8.0-composer-${{ hashFiles('composer.json') }}
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          coverage: none
      - name: Install Dependencies
        run: composer install --no-suggest --prefer-dist -n -o
      - name: Run Code Styles Check
        run: vendor/bin/phpcs